services:
  postgres:
    image: postgres:17-alpine
    container_name: triad-db
    environment:
      POSTGRES_DB: parts_catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U admin -d parts_catalog -c 'SELECT 1 FROM startup_completed LIMIT 1'"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s

  helidon-app:
    build: ./partscatalog-java
    container_name: triad-helidon
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=parts_catalog
      - DB_USER=admin
      - DB_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
